// Id: ObjectID,
// firstName: String,
// lastName: String,
// dateOfBirth: String,
// gender: String,
// emailId: String,
// password: String,
// profilePicture: String,
// role: [“ADMIN”, “STUDENT”, “COMPANY_EMPLOYEE”],
// isPremiumUser: boolean,
// appliedJobs: [Jobs]
